### ISSUE TITLE
AttributeError: 'ProposalLayer' object has no attribute 'param_str'

### ISSUE THREAD

**Issue by annw0922** [playerkk/face-py-faster-rcnn#22]
Hello,

Traceback (most recent call last):
  File "./tools/train_net.py", line 114, in <module>
    max_iters=args.max_iters)
  File "/home/wangyj/face-py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 157, in train_net
    pretrained_model=pretrained_model)
  File "/home/wangyj/face-py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 43, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
  File "/home/wangyj/face-py-faster-rcnn/tools/../lib/rpn/proposal_layer.py", line 26, in setup
    layer_params = yaml.load(self.param_str)
AttributeError: 'ProposalLayer' object has no attribute 'param_str'

I just followed your step and met this problem, I have totally no idea as I met this here but I didn't met when I run faster-rcnn

**Comment by annw0922** [comment]
.... I changed 'param_str' to 'param_str_' and then fixed it , maybe because of the version of caffe

**Comment by lxtGH** [comment]
@annw0922  Hi what version  faster-rcnn you use???
